# Generated by Django 5.2.15 on 2026-06-18 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('sku', models.CharField(default='', max_length=100, unique=True)),
                ('size', models.CharField(default='', max_length=10)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.CharField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured_product', models.BooleanField(default=False)),
                ('category', models.CharField(default='')),
                ('slogan', models.CharField(default='')),
            ],
        ),
    ]
