# Generated by Django 5.2.15 on 2026-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1_url',
        ),
        migrations.AddField(
            model_name='products',
            name='image2_url',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image3_url',
            field=models.CharField(default=''),
        ),
    ]
