# Generated by Django 5.2.15 on 2026-06-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_products_image1_url_products_image2_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
